[2022-10-04 12:05:40,826] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: agg_star_wars.aggregation_of_data manual__2022-10-04T12:05:35.271110+00:00 [queued]>
[2022-10-04 12:05:40,852] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: agg_star_wars.aggregation_of_data manual__2022-10-04T12:05:35.271110+00:00 [queued]>
[2022-10-04 12:05:40,853] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-10-04 12:05:40,855] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-10-04 12:05:40,857] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-10-04 12:05:40,888] {taskinstance.py:1259} INFO - Executing <Task(PostgresOperator): aggregation_of_data> on 2022-10-04 12:05:37.110100+00:00
[2022-10-04 12:05:40,895] {standard_task_runner.py:52} INFO - Started process 356 to run task
[2022-10-04 12:05:40,902] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'agg_star_wars', 'aggregation_of_data', 'manual__2022-10-04T12:05:35.271110+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/star_wars_agg.py', '--cfg-path', '/tmp/tmpipmem83c', '--error-file', '/tmp/tmpwvmdx6ob']
[2022-10-04 12:05:40,904] {standard_task_runner.py:77} INFO - Job 31: Subtask aggregation_of_data
[2022-10-04 12:05:41,052] {logging_mixin.py:109} INFO - Running <TaskInstance: agg_star_wars.aggregation_of_data manual__2022-10-04T12:05:35.271110+00:00 [running]> on host be1a5b89e146
[2022-10-04 12:05:41,277] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=xxxx@xxxxx.com
AIRFLOW_CTX_DAG_OWNER=Anvesh
AIRFLOW_CTX_DAG_ID=agg_star_wars
AIRFLOW_CTX_TASK_ID=aggregation_of_data
AIRFLOW_CTX_EXECUTION_DATE=2022-10-04T12:05:37.110100+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-04T12:05:35.271110+00:00
[2022-10-04 12:05:41,317] {base.py:79} INFO - Using connection to: id: postgres_local. Host: host.docker.internal, Port: 5432, Schema: postgres, Login: postgres, Password: ***, extra: {}
[2022-10-04 12:05:41,459] {dbapi.py:225} INFO - Running statement: TRUNCATE star_wars_agg_data;
INSERT INTO star_wars_agg_data SELECT * FROM

(SELECT d.title,d.name from

( SELECT c.title,c.name, RANK () OVER (PARTITION BY c.title ORDER BY c.age DESC)  as age_rank

 FROM
(SELECT b.title , a.name , a.birth_year,
 CASE WHEN a.age_decider = 'BBY' THEN CAST(LEFT(a.birth_year,-3) as FLOAT)
								 ELSE CAST(LEFT(a.birth_year,-3) as FLOAT)*-1 end as age

FROM (SELECT name,birth_year,RIGHT(birth_year,3) as age_decider,
replace(unnest(string_to_array ((replace(replace(replace(films,'''',''),'[',''),']','')),',')),' ','')
as film

	  FROM star_wars_people) a
INNER JOIN star_wars_films as b on a.film=b.url
WHERE a.birth_year != 'unknown') c )d

WHERE age_rank =1) e




, parameters: None
[2022-10-04 12:05:41,502] {dbapi.py:233} INFO - Rows affected: 4
[2022-10-04 12:05:41,535] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=agg_star_wars, task_id=aggregation_of_data, execution_date=20221004T120537, start_date=20221004T120540, end_date=20221004T120541
[2022-10-04 12:05:41,615] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-10-04 12:05:41,662] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
