[2022-10-04 13:28:25,580] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_star_wars.create_films_table manual__2022-10-04T13:28:23.237734+00:00 [queued]>
[2022-10-04 13:28:25,593] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_star_wars.create_films_table manual__2022-10-04T13:28:23.237734+00:00 [queued]>
[2022-10-04 13:28:25,594] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-10-04 13:28:25,595] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-10-04 13:28:25,596] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-10-04 13:28:25,607] {taskinstance.py:1259} INFO - Executing <Task(PostgresOperator): create_films_table> on 2022-10-04 13:28:23.237734+00:00
[2022-10-04 13:28:25,615] {standard_task_runner.py:52} INFO - Started process 3798 to run task
[2022-10-04 13:28:25,621] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_star_wars', 'create_films_table', 'manual__2022-10-04T13:28:23.237734+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/ingest_starwars_data.py', '--cfg-path', '/tmp/tmp2z5zwjur', '--error-file', '/tmp/tmpe4icp2tr']
[2022-10-04 13:28:25,624] {standard_task_runner.py:77} INFO - Job 32: Subtask create_films_table
[2022-10-04 13:28:25,697] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_star_wars.create_films_table manual__2022-10-04T13:28:23.237734+00:00 [running]> on host be1a5b89e146
[2022-10-04 13:28:25,763] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=xxxx@xxxxx.com
AIRFLOW_CTX_DAG_OWNER=Ram
AIRFLOW_CTX_DAG_ID=ingest_star_wars
AIRFLOW_CTX_TASK_ID=create_films_table
AIRFLOW_CTX_EXECUTION_DATE=2022-10-04T13:28:23.237734+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-04T13:28:23.237734+00:00
[2022-10-04 13:28:25,775] {base.py:79} INFO - Using connection to: id: postgres_local. Host: host.docker.internal, Port: 5432, Schema: postgres, Login: postgres, Password: ***, extra: {}
[2022-10-04 13:28:25,853] {dbapi.py:225} INFO - Running statement: CREATE TABLE IF NOT EXISTS star_wars_films (
            title TEXT,
            episode_id TEXT,
            opening_crawl TEXT,
            director TEXT,
            producer TEXT,
            release_date TEXT,
            characters TEXT,
            planets TEXT,
            starships TEXT,
            vehicles TEXT,
            species TEXT,
            created TEXT,
            edited TEXT,
            url TEXT
            );, parameters: None
[2022-10-04 13:28:25,867] {postgres.py:71} INFO - NOTICE:  relation "star_wars_films" already exists, skipping

[2022-10-04 13:28:25,897] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_star_wars, task_id=create_films_table, execution_date=20221004T132823, start_date=20221004T132825, end_date=20221004T132825
[2022-10-04 13:28:25,924] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-10-04 13:28:25,976] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
